# Site
name: 'UConnPSIG'
description: 'University of Connecticut Plastic Surgery Interest Group'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
disqus: 'https-uconnpsig-github-io'
email: 'uconnstudentplastics@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    jillian:
      name:           Dr. Jillian Fortier
      site:           
      avatar:         /assets/images/jillian.jpg
      bio:            "Faculty Advisor, Plastic Surgeon, Assistant Professor of Surgery"
      email:          jfortier@uchc.edu
      twitter: 

    ian:
      name:           Ian Whittall
      site:           
      avatar:         /assets/images/ian.jpg
      bio:            "MS3, Co-founder"
      email:          whittall@uchc.edu
      twitter:  

    ian:
      name:           Maria Slater
      site:           
      avatar:         /assets/images/maria.jpg
      bio:            "MS3, Co-founder"
      email:          mslater@uchc.edu
      twitter:  
    
    newlyn:
      name:           Newlyn Joseph
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "I'm a 2nd year medical student interested in reconstructive plastic surgery. When he’s not studying or at clinic he enjoys binging Botched and catching up on sleep. I enjoy cooking, playing guitar, and swimming in my down time."
      email:          nejoseph@uchc.edu
      twitter:        https://twitter.com/newlynjoseph

    annie:
      name:           Annie Jin
      site:           
      avatar:         /assets/images/annie.png
      bio:            "My name is Annie Jin and I am a second year medical student at the University of Connecticut. I am from Connecticut, and in my free time I enjoy running, drawing, cooking, and dancing."
      email:          ajin@uchc.edu
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: annie
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
